#!/bin/bash

# Color Definitions for text color (tput)
    # Based on solarized color theme from https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized#the-values

black=$(tput setaf 0);
blue=$(tput setaf 33);
cyan=$(tput setaf 37);
green=$(tput setaf 64);
orange=$(tput setaf 166);
purple=$(tput setaf 125);
red=$(tput setaf 124);
violet=$(tput setaf 61);
white=$(tput setaf 15);
yellow=$(tput setaf 136);